services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://construction_user:construction_password@postgres:5432/construction
    networks:
      - construction
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node build
      "

networks:
  construction:
    external: true
