services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      ORIGIN: 'https://skrusdom.ru'
      DATABASE_URL: postgres://construction_user:construction_password@postgres:5432/construction
      BODY_SIZE_LIMIT: 200000000
    networks:
      - construction

networks:
  construction:
    external: true
