services:
  app:
    build: .
    ports:
      - '3000:3000'
    networks:
      - construction
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node build
      "

networks:
  construction:
    external: true
