services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./logs:/app/logs
      - uploads:/app/uploads
    environment:
      ORIGIN: 'https://skrusdom.ru'
      DATABASE_URL: postgres://construction_user:construction_password@postgres:5432/construction
      BODY_SIZE_LIMIT: 200000000
    networks:
      - construction

  picture-backup:
    image: alpine
    volumes:
      - uploads:/data:ro # read-only access to uploaded pictures
      - ./backups/pictures:/backups # backups stored on host
    entrypoint: >
      sh -c "tar -czf /backups/uploads_$(date +%F_%H-%M-%S).tar.gz /data"

  postgres:
    image: postgres:17
    container_name: construction-postgres
    environment:
      POSTGRES_USER: construction_user
      POSTGRES_PASSWORD: construction_password
      POSTGRES_DB: construction
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - construction

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - /var/opt/pgbackups:/backups
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=construction
      - POSTGRES_USER=construction_user
      - POSTGRES_PASSWORD=construction_password
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_ON_START=TRUE
      - BACKUP_KEEP_WEEKS=2
      - HEALTHCHECK_PORT=8080
    networks:
      - construction

  prisma-migrate:
    container_name: prisma-migrate
    build: ./prisma
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres

volumes:
  pgdata:

networks:
  construction:
    external: true
